In [ ]:
import numpy as np

numeros = np.array([1,2,3])
valor = 5 #Em vez de criar outro array para calculos, consigo fazer o mesmo calculo atribuindo a uma variavel valor, tambem funciona com matriz

numeros + valor

array([6, 7, 8])

### Desafio 1
Dado o seguinte array, some o valor 10 a cada elemento usando broadcasting

In [2]:
array = np.array([10,20,30,40,50])
valor = 10

array + valor

array([20, 30, 40, 50, 60])

### Desafio 2
Dada a matriz abaixo, subtraia o array[5,5] de cada linha usando broadcating

In [3]:
matriz = np.array([[5,10],[15,20],[25,30]])
array = np.array([5,5])

matriz - array

array([[ 0,  5],
       [10, 15],
       [20, 25]])

### Desafio 3
Multiplique cada coluna da matriz abaixo pelo array [2,3]

In [4]:
matriz = np.array([[5,10],[15,20],[25,30]])
array = np.array([2,3])

matriz * array

array([[10, 30],
       [30, 60],
       [50, 90]])