In [11]:
import numpy as np

numeros = np.array([2,4,6,8,10])
numeros[3] #Acessar por indice
numeros[-1] #Acessar ultimo valor

numeros[2:4] # Acessa o valor 6 e 8
numeros[1:3] # Acessa o valor 4 e 6
numeros[1:] #Acessando os valores ate o final

#Inciar no primeiro item e ir até o final, extraindo os valor de cada 2 indices
numeros2 = np.array([10,20,30,40,50,60,70])
numeros2[::2]

#Array[indice_inicial:indice_final:pulo]
numeros2[0:5:2]

#Indice em matrizes
matriz = np.array([[1,2,4],[5,6,7]])
matriz[1,1]

#Fatiamento em matrizes
matriz = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
matriz[0:2,0:2]

#Fatiamento condicional
valores = np.array([10,20,30,40,50])
valores[(valores > 20) & (valores < 50)]
valores[(valores == 10) | (valores == 40)]

array([10, 40])

### Desafio 1
Dado o array abaixo, exiba os 3 primeiros elementos

In [13]:
numeros = [3,6,9,12,15]
numeros[0:3]

[3, 6, 9]

### Desafio 2
Dado o array abaixo, exiba os numeros impares usando fatiamento

In [22]:
outros_numeros = [3,6,9,12,15]
impares = [num for num in outros_numeros if num % 2 != 0]
impares

[3, 9, 15]

### Desafio 3
Dada a matriz abaixo, exiba os valores da terceira coluna de todas as linhas

In [133]:
matriz = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

matriz[0:3,2]

array([3, 6, 9])

### Desafio 4
Da matriz abaixo, exiba os elementos das duas primeiras linhas e da primeira coluna

In [131]:
matriz = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

matriz[0:2,0]

array([1, 4])

### Desafio 5
Dado o array abaixo, exiba os numeros que são menores que 20 ou maiores que 25

In [130]:
valores = np.array([5,10,15,20,25,30])
valores[(valores < 20) | (valores > 25)]

array([ 5, 10, 15, 30])