In [4]:
import numpy as np

# Manipulação do shape de arrays e matrizes
vendas = np.array([100, 200, 150, 170])

vendas_loja_1 = np.array([[759, 450],
                          [350, 299]])

vendas_loja_2 = np.array([[250, 298],
                          [355, 295],
                          [775, 135]]) #3x2 ->2x3

vendas_loja_3 = np.array([[852, 199],
                          [123, 345],
                          [465, 678],
                          [345,644]]) # 4x2 ->2x4 -> 8x1

print("Shape array vendas:", vendas.shape)
print("Shape matriz vendas_loja_1:", vendas_loja_1.shape)
print("Shape matriz vendas_loja_2:", vendas_loja_2.shape)
print("Shape matriz vendas_loja_3:", vendas_loja_3.shape)

# Reshape - Alterar o shape(formato de um array ou matriz)
print(f'Shape array vendas: {vendas.reshape(2,2)}')
print(f'Shape vendas_loja_2 = {vendas_loja_2.reshape(2,3)}')
print(f'Shape vendas_loja_3 = {vendas_loja_3.reshape(8,1)}')

# Transposição - (inverter as dimensões de um array)
nova_vendas_loja_2_transposta = vendas_loja_2.T
print(nova_vendas_loja_2_transposta)

Shape array vendas: (4,)
Shape matriz vendas_loja_1: (2, 2)
Shape matriz vendas_loja_2: (3, 2)
Shape matriz vendas_loja_3: (4, 2)
Shape array vendas: [[100 200]
 [150 170]]
Shape vendas_loja_2 = [[250 298 355]
 [295 775 135]]
Shape vendas_loja_3 = [[852]
 [199]
 [123]
 [345]
 [465]
 [678]
 [345]
 [644]]
[[250 355 775]
 [298 295 135]]


### Desafio 1 
Crie um array com valores de 1 a 8 e depois o transforme em uma matriz 4x2

In [18]:
valores = np.arange(1,9)
valores.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

### Desafio 2
Dada a matriz abaixo, transponha-a

In [17]:
matriz = np.array([[1,2,3],[4,5,6]])
nova_matriz = matriz.T
print(nova_matriz)

[[1 4]
 [2 5]
 [3 6]]


### Desafio 3
Verifique o shape do array transposto no desafio 2

In [19]:
nova_matriz.shape

(3, 2)