In [10]:
import numpy as np

dados = np.array([1,2,3,4,5,6])

#Multiplos indices
indices = [0,3,5]
dados[indices]

#Janela deslizante - list compreheension

np.random.seed(30)
temperaturas = np.random.randint(5,35,30) # Gerar um array de 30 temperaturas aleatorias
temperaturas

tamanho_janela = 7
janelas_temperaturas = [temperaturas[i:i+tamanho_janela] for i in range(0,len(temperaturas) - tamanho_janela + 1,7)]
janelas_temperaturas

#Qual a media de temperatura a cada semana ?
for temp in janelas_temperaturas:
    print(np.mean(temp))
    


18.0
18.285714285714285
18.285714285714285
20.714285714285715


### Desafio 1
A partir do array abaixo de 30 pesos diferentes, gere 3 arrays a partir de uma janela deslizante de 10 itens, coloque este resultado em uma variável chamada faixa_pesos e imprima o resultado com um laço for

In [ ]:
np.random.seed(1337)
pesos = np.random.randint(50,120,30) # [ 73, 111,  89,  89,  59,  56, 104,  73,  74,  51,  77,  56,  72,116, 115, 110,  69, 101, 107, 117,  70,  58, 111,  59, 118,  56,118,  96,  70,  68]

janela1 = 10
# Metodo list comprehension
faixa_pesos = [pesos[i:i+janela1] for i in range(0,len(pesos) - janela1 + 1,10)]
faixa_pesos

for faixa in faixa_pesos:
    print(faixa)

[ 73 111  89  89  59  56 104  73  74  51]
[ 77  56  72 116 115 110  69 101 107 117]
[ 70  58 111  59 118  56 118  96  70  68]


### Desafio 2
A partir da variável faixa_pesos, faça duas list comprehensions para resolver os seguintes problemas:
a) Encontre o desvio padrão de cada faixa de peso, guarde isso numa variável chamada desvio_padrão e imprima o resultado na tela
b) Encontre o valor máximo entre cada faixa de peso, guarde isso numa variável chamada pesos_máximo e imprima o resultado na tela

In [ ]:
#a)
desvio_padrao = [np.std(faixa) for faixa in faixa_pesos]
print(desvio_padrao)

[np.float64(19.096858380372414), np.float64(21.840329667841555), np.float64(24.274266209300745)]


In [33]:
#b)
pesos_maximo = [np.max(faixa) for faixa in faixa_pesos]
print(pesos_maximo)

[np.int32(111), np.int32(117), np.int32(118)]
